// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $AddToCartButton_linx from "./islands/AddToCartButton/linx.tsx";
import * as $AddToCartButton_nuvemshop from "./islands/AddToCartButton/nuvemshop.tsx";
import * as $AddToCartButton_shopify from "./islands/AddToCartButton/shopify.tsx";
import * as $AddToCartButton_vnda from "./islands/AddToCartButton/vnda.tsx";
import * as $AddToCartButton_vtex from "./islands/AddToCartButton/vtex.tsx";
import * as $AddToCartButton_wake from "./islands/AddToCartButton/wake.tsx";
import * as $AdminNewDocModal from "./islands/AdminNewDocModal.tsx";
import * as $AdminOrders from "./islands/AdminOrders.tsx";
import * as $AssociationAdmin from "./islands/AssociationAdmin.tsx";
import * as $Chart from "./islands/Chart.tsx";
import * as $CheckoutForm from "./islands/CheckoutForm.tsx";
import * as $CheckoutFormPrescriber from "./islands/CheckoutFormPrescriber.tsx";
import * as $CheckoutUpsellModal from "./islands/CheckoutUpsellModal.tsx";
import * as $ChoosePlanSignup from "./islands/ChoosePlanSignup.tsx";
import * as $ChoosePlanSignupPrescriber from "./islands/ChoosePlanSignupPrescriber.tsx";
import * as $ConfirmForgotPasswordForm from "./islands/ConfirmForgotPasswordForm.tsx";
import * as $ConfirmPrescriberSignup from "./islands/ConfirmPrescriberSignup.tsx";
import * as $ConfirmSignup from "./islands/ConfirmSignup.tsx";
import * as $EcannaCardPage from "./islands/EcannaCardPage.tsx";
import * as $ForgotPasswordForm from "./islands/ForgotPasswordForm.tsx";
import * as $FreshChart from "./islands/FreshChart.tsx";
import * as $Header_Buttons from "./islands/Header/Buttons.tsx";
import * as $Header_Cart_linx from "./islands/Header/Cart/linx.tsx";
import * as $Header_Cart_nuvemshop from "./islands/Header/Cart/nuvemshop.tsx";
import * as $Header_Cart_shopify from "./islands/Header/Cart/shopify.tsx";
import * as $Header_Cart_vnda from "./islands/Header/Cart/vnda.tsx";
import * as $Header_Cart_vtex from "./islands/Header/Cart/vtex.tsx";
import * as $Header_Cart_wake from "./islands/Header/Cart/wake.tsx";
import * as $Header_Drawers from "./islands/Header/Drawers.tsx";
import * as $Header_Searchbar from "./islands/Header/Searchbar.tsx";
import * as $MyAccount from "./islands/MyAccount.tsx";
import * as $MyDocs from "./islands/MyDocs.tsx";
import * as $MyInfo from "./islands/MyInfo.tsx";
import * as $MyOrders from "./islands/MyOrders.tsx";
import * as $NewTicketModal from "./islands/NewTicketModal.tsx";
import * as $Newsletter from "./islands/Newsletter.tsx";
import * as $OutOfStock from "./islands/OutOfStock.tsx";
import * as $PatientNewTreatmentEntry from "./islands/PatientNewTreatmentEntry.tsx";
import * as $PatientNewTreatmentEntryLive from "./islands/PatientNewTreatmentEntryLive.tsx";
import * as $PatientTreatment from "./islands/PatientTreatment.tsx";
import * as $PatientTreatmentLive from "./islands/PatientTreatmentLive.tsx";
import * as $PatientTreatmentReport from "./islands/PatientTreatmentReport.tsx";
import * as $PatientTreatmentReportLive from "./islands/PatientTreatmentReportLive.tsx";
import * as $PreSignupUsersModal from "./islands/PreSignupUsersModal.tsx";
import * as $PrescriberNewPatientModal from "./islands/PrescriberNewPatientModal.tsx";
import * as $PrescriberNewPatientModalLive from "./islands/PrescriberNewPatientModalLive.tsx";
import * as $PrescriberPatientTreatment from "./islands/PrescriberPatientTreatment.tsx";
import * as $PrescriberPatientTreatmentLive from "./islands/PrescriberPatientTreatmentLive.tsx";
import * as $PrescriberPatientTreatmentReport from "./islands/PrescriberPatientTreatmentReport.tsx";
import * as $PrescriberPatientTreatmentReportLive from "./islands/PrescriberPatientTreatmentReportLive.tsx";
import * as $PrescriberPatients from "./islands/PrescriberPatients.tsx";
import * as $PrescriberPatientsLive from "./islands/PrescriberPatientsLive.tsx";
import * as $PrescriberUpdateTreatmentModal from "./islands/PrescriberUpdateTreatmentModal.tsx";
import * as $PrescriberUpdateTreatmentModalLive from "./islands/PrescriberUpdateTreatmentModalLive.tsx";
import * as $PrivatePageControl from "./islands/PrivatePageControl.tsx";
import * as $PrivatePageControlAdmin from "./islands/PrivatePageControlAdmin.tsx";
import * as $PrivatePageControlPrescriber from "./islands/PrivatePageControlPrescriber.tsx";
import * as $ProductImageZoom from "./islands/ProductImageZoom.tsx";
import * as $PublicPageControl from "./islands/PublicPageControl.tsx";
import * as $SearchControls from "./islands/SearchControls.tsx";
import * as $ShippingSimulation from "./islands/ShippingSimulation.tsx";
import * as $ShowMore from "./islands/ShowMore.tsx";
import * as $SignInForm from "./islands/SignInForm.tsx";
import * as $SignInFormAdmin from "./islands/SignInFormAdmin.tsx";
import * as $SignInFormPrescriber from "./islands/SignInFormPrescriber.tsx";
import * as $SignUpForm from "./islands/SignUpForm.tsx";
import * as $SignUpFormPrescriber from "./islands/SignUpFormPrescriber.tsx";
import * as $Signout from "./islands/Signout.tsx";
import * as $SliderJS from "./islands/SliderJS.tsx";
import * as $UserAlerts from "./islands/UserAlerts.tsx";
import * as $UserAssociatedSignup from "./islands/UserAssociatedSignup.tsx";
import * as $WishlistButton_vtex from "./islands/WishlistButton/vtex.tsx";
import * as $WishlistButton_wake from "./islands/WishlistButton/wake.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
  },
  islands: {
    "./islands/AddToCartButton/linx.tsx": $AddToCartButton_linx,
    "./islands/AddToCartButton/nuvemshop.tsx": $AddToCartButton_nuvemshop,
    "./islands/AddToCartButton/shopify.tsx": $AddToCartButton_shopify,
    "./islands/AddToCartButton/vnda.tsx": $AddToCartButton_vnda,
    "./islands/AddToCartButton/vtex.tsx": $AddToCartButton_vtex,
    "./islands/AddToCartButton/wake.tsx": $AddToCartButton_wake,
    "./islands/AdminNewDocModal.tsx": $AdminNewDocModal,
    "./islands/AdminOrders.tsx": $AdminOrders,
    "./islands/AssociationAdmin.tsx": $AssociationAdmin,
    "./islands/Chart.tsx": $Chart,
    "./islands/CheckoutForm.tsx": $CheckoutForm,
    "./islands/CheckoutFormPrescriber.tsx": $CheckoutFormPrescriber,
    "./islands/CheckoutUpsellModal.tsx": $CheckoutUpsellModal,
    "./islands/ChoosePlanSignup.tsx": $ChoosePlanSignup,
    "./islands/ChoosePlanSignupPrescriber.tsx": $ChoosePlanSignupPrescriber,
    "./islands/ConfirmForgotPasswordForm.tsx": $ConfirmForgotPasswordForm,
    "./islands/ConfirmPrescriberSignup.tsx": $ConfirmPrescriberSignup,
    "./islands/ConfirmSignup.tsx": $ConfirmSignup,
    "./islands/EcannaCardPage.tsx": $EcannaCardPage,
    "./islands/ForgotPasswordForm.tsx": $ForgotPasswordForm,
    "./islands/FreshChart.tsx": $FreshChart,
    "./islands/Header/Buttons.tsx": $Header_Buttons,
    "./islands/Header/Cart/linx.tsx": $Header_Cart_linx,
    "./islands/Header/Cart/nuvemshop.tsx": $Header_Cart_nuvemshop,
    "./islands/Header/Cart/shopify.tsx": $Header_Cart_shopify,
    "./islands/Header/Cart/vnda.tsx": $Header_Cart_vnda,
    "./islands/Header/Cart/vtex.tsx": $Header_Cart_vtex,
    "./islands/Header/Cart/wake.tsx": $Header_Cart_wake,
    "./islands/Header/Drawers.tsx": $Header_Drawers,
    "./islands/Header/Searchbar.tsx": $Header_Searchbar,
    "./islands/MyAccount.tsx": $MyAccount,
    "./islands/MyDocs.tsx": $MyDocs,
    "./islands/MyInfo.tsx": $MyInfo,
    "./islands/MyOrders.tsx": $MyOrders,
    "./islands/NewTicketModal.tsx": $NewTicketModal,
    "./islands/Newsletter.tsx": $Newsletter,
    "./islands/OutOfStock.tsx": $OutOfStock,
    "./islands/PatientNewTreatmentEntry.tsx": $PatientNewTreatmentEntry,
    "./islands/PatientNewTreatmentEntryLive.tsx": $PatientNewTreatmentEntryLive,
    "./islands/PatientTreatment.tsx": $PatientTreatment,
    "./islands/PatientTreatmentLive.tsx": $PatientTreatmentLive,
    "./islands/PatientTreatmentReport.tsx": $PatientTreatmentReport,
    "./islands/PatientTreatmentReportLive.tsx": $PatientTreatmentReportLive,
    "./islands/PreSignupUsersModal.tsx": $PreSignupUsersModal,
    "./islands/PrescriberNewPatientModal.tsx": $PrescriberNewPatientModal,
    "./islands/PrescriberNewPatientModalLive.tsx":
      $PrescriberNewPatientModalLive,
    "./islands/PrescriberPatientTreatment.tsx": $PrescriberPatientTreatment,
    "./islands/PrescriberPatientTreatmentLive.tsx":
      $PrescriberPatientTreatmentLive,
    "./islands/PrescriberPatientTreatmentReport.tsx":
      $PrescriberPatientTreatmentReport,
    "./islands/PrescriberPatientTreatmentReportLive.tsx":
      $PrescriberPatientTreatmentReportLive,
    "./islands/PrescriberPatients.tsx": $PrescriberPatients,
    "./islands/PrescriberPatientsLive.tsx": $PrescriberPatientsLive,
    "./islands/PrescriberUpdateTreatmentModal.tsx":
      $PrescriberUpdateTreatmentModal,
    "./islands/PrescriberUpdateTreatmentModalLive.tsx":
      $PrescriberUpdateTreatmentModalLive,
    "./islands/PrivatePageControl.tsx": $PrivatePageControl,
    "./islands/PrivatePageControlAdmin.tsx": $PrivatePageControlAdmin,
    "./islands/PrivatePageControlPrescriber.tsx": $PrivatePageControlPrescriber,
    "./islands/ProductImageZoom.tsx": $ProductImageZoom,
    "./islands/PublicPageControl.tsx": $PublicPageControl,
    "./islands/SearchControls.tsx": $SearchControls,
    "./islands/ShippingSimulation.tsx": $ShippingSimulation,
    "./islands/ShowMore.tsx": $ShowMore,
    "./islands/SignInForm.tsx": $SignInForm,
    "./islands/SignInFormAdmin.tsx": $SignInFormAdmin,
    "./islands/SignInFormPrescriber.tsx": $SignInFormPrescriber,
    "./islands/SignUpForm.tsx": $SignUpForm,
    "./islands/SignUpFormPrescriber.tsx": $SignUpFormPrescriber,
    "./islands/Signout.tsx": $Signout,
    "./islands/SliderJS.tsx": $SliderJS,
    "./islands/UserAlerts.tsx": $UserAlerts,
    "./islands/UserAssociatedSignup.tsx": $UserAssociatedSignup,
    "./islands/WishlistButton/vtex.tsx": $WishlistButton_vtex,
    "./islands/WishlistButton/wake.tsx": $WishlistButton_wake,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
