// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/changePassword.ts";
import * as $$$$$$$$$1 from "./actions/checkout.ts";
import * as $$$$$$$$$2 from "./actions/cognitoSignIn.ts";
import * as $$$$$$$$$3 from "./actions/cognitoSignUp.ts";
import * as $$$$$$$$$4 from "./actions/confirmCognitoSignup.ts";
import * as $$$$$$$$$5 from "./actions/confirmForgotPassword.ts";
import * as $$$$$$$$$6 from "./actions/createTicket.ts";
import * as $$$$$$$$$7 from "./actions/deleteDocument.ts";
import * as $$$$$$$$$8 from "./actions/forgotPassword.ts";
import * as $$$$$$$$$9 from "./actions/getAssociation.ts";
import * as $$$$$$$$$10 from "./actions/getCids.ts";
import * as $$$$$$$$$11 from "./actions/getDocs.ts";
import * as $$$$$$$$$12 from "./actions/getPlans.ts";
import * as $$$$$$$$$13 from "./actions/getProfile.ts";
import * as $$$$$$$$$14 from "./actions/getUser.ts";
import * as $$$$$$$$$15 from "./actions/resendConfirmationCode.ts";
import * as $$$$$$$$$16 from "./actions/updateProfile.ts";
import * as $$$$$$$$$17 from "./actions/updateUserData.ts";
import * as $$$$$$$$$18 from "./actions/uploadFile.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$2 from "./loaders/availableIcons.ts";
import * as $$$3 from "./loaders/getPublicProfile.ts";
import * as $$$4 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/Layouts/ProductCard.tsx";
import * as $$$1 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$2 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$3 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$4 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$6 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$7 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$8 from "./sections/Content/Benefits.tsx";
import * as $$$$$$9 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$10 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$11 from "./sections/Content/Faq.tsx";
import * as $$$$$$12 from "./sections/Content/FaqPublicProfile.tsx";
import * as $$$$$$13 from "./sections/Content/Features.tsx";
import * as $$$$$$14 from "./sections/Content/Hero.tsx";
import * as $$$$$$15 from "./sections/Content/ImageSection.tsx";
import * as $$$$$$16 from "./sections/Content/Intro.tsx";
import * as $$$$$$17 from "./sections/Content/Logos.tsx";
import * as $$$$$$18 from "./sections/Content/Partners.tsx";
import * as $$$$$$19 from "./sections/Content/RichText.tsx";
import * as $$$$$$20 from "./sections/Content/Support.tsx";
import * as $$$$$$21 from "./sections/Content/Table.tsx";
import * as $$$$$$22 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$23 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$24 from "./sections/Footer/Footer.tsx";
import * as $$$$$$25 from "./sections/Gallery.tsx";
import * as $$$$$$26 from "./sections/Header/Header.tsx";
import * as $$$$$$27 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$28 from "./sections/Images/Carousel.tsx";
import * as $$$$$$29 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$30 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$31 from "./sections/Layout/Container.tsx";
import * as $$$$$$32 from "./sections/Layout/Flex.tsx";
import * as $$$$$$33 from "./sections/Layout/Grid.tsx";
import * as $$$$$$34 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$35 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$36 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$37 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$38 from "./sections/Miscellaneous/Checkout.tsx";
import * as $$$$$$39 from "./sections/Miscellaneous/ChoosePlanSignup.tsx";
import * as $$$$$$40 from "./sections/Miscellaneous/ConfirmForgotPassword.tsx";
import * as $$$$$$41 from "./sections/Miscellaneous/ConfirmSignup.tsx";
import * as $$$$$$42 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$43 from "./sections/Miscellaneous/EcannaCardPage.tsx";
import * as $$$$$$44 from "./sections/Miscellaneous/ForgotPassword.tsx";
import * as $$$$$$45 from "./sections/Miscellaneous/MyAccount.tsx";
import * as $$$$$$46 from "./sections/Miscellaneous/MyDocs.tsx";
import * as $$$$$$47 from "./sections/Miscellaneous/MyInfo.tsx";
import * as $$$$$$48 from "./sections/Miscellaneous/PrivatePageControl.tsx";
import * as $$$$$$49 from "./sections/Miscellaneous/PublicPageControl.tsx";
import * as $$$$$$50 from "./sections/Miscellaneous/PublicProfile.tsx";
import * as $$$$$$51 from "./sections/Miscellaneous/SignIn.tsx";
import * as $$$$$$53 from "./sections/Miscellaneous/Signout.tsx";
import * as $$$$$$52 from "./sections/Miscellaneous/SignUp.tsx";
import * as $$$$$$54 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$55 from "./sections/Miscellaneous/UserAlerts.tsx";
import * as $$$$$$56 from "./sections/Miscellaneous/UserAssociatedSignup.tsx";
import * as $$$$$$57 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$58 from "./sections/Product/ImageGalleryFrontBack.tsx";
import * as $$$$$$59 from "./sections/Product/ImageGallerySlider.tsx";
import * as $$$$$$60 from "./sections/Product/NotFound.tsx";
import * as $$$$$$61 from "./sections/Product/NotFoundChallenge.tsx";
import * as $$$$$$62 from "./sections/Product/ProductDetails.tsx";
import * as $$$$$$63 from "./sections/Product/ProductInfo.tsx";
import * as $$$$$$64 from "./sections/Product/ProductShelf.tsx";
import * as $$$$$$65 from "./sections/Product/ProductShelfTabbed.tsx";
import * as $$$$$$66 from "./sections/Product/SearchResult.tsx";
import * as $$$$$$67 from "./sections/Product/ShelfWithImage.tsx";
import * as $$$$$$68 from "./sections/Product/Wishlist.tsx";
import * as $$$$$$69 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$70 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$71 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/ecannadeco/loaders/availableIcons.ts": $$$2,
    "deco-sites/ecannadeco/loaders/getPublicProfile.ts": $$$3,
    "deco-sites/ecannadeco/loaders/icons.ts": $$$4,
    "deco-sites/ecannadeco/loaders/Layouts/ProductCard.tsx": $$$0,
    "deco-sites/ecannadeco/loaders/List/Sections.tsx": $$$1,
  },
  "sections": {
    "deco-sites/ecannadeco/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/ecannadeco/sections/Cards/IconCardsCarousel.tsx": $$$$$$1,
    "deco-sites/ecannadeco/sections/Cards/IconCardsCarouselWithImage.tsx":
      $$$$$$2,
    "deco-sites/ecannadeco/sections/Cards/ImageCardsCarousel.tsx": $$$$$$3,
    "deco-sites/ecannadeco/sections/Cards/ImageCardsCarouselWithImage.tsx":
      $$$$$$4,
    "deco-sites/ecannadeco/sections/Category/CategoryBanner.tsx": $$$$$$5,
    "deco-sites/ecannadeco/sections/Category/CategoryGrid.tsx": $$$$$$6,
    "deco-sites/ecannadeco/sections/Category/CategoryList.tsx": $$$$$$7,
    "deco-sites/ecannadeco/sections/Content/Benefits.tsx": $$$$$$8,
    "deco-sites/ecannadeco/sections/Content/BlogPosts.tsx": $$$$$$9,
    "deco-sites/ecannadeco/sections/Content/CallToAction.tsx": $$$$$$10,
    "deco-sites/ecannadeco/sections/Content/Faq.tsx": $$$$$$11,
    "deco-sites/ecannadeco/sections/Content/FaqPublicProfile.tsx": $$$$$$12,
    "deco-sites/ecannadeco/sections/Content/Features.tsx": $$$$$$13,
    "deco-sites/ecannadeco/sections/Content/Hero.tsx": $$$$$$14,
    "deco-sites/ecannadeco/sections/Content/ImageSection.tsx": $$$$$$15,
    "deco-sites/ecannadeco/sections/Content/Intro.tsx": $$$$$$16,
    "deco-sites/ecannadeco/sections/Content/Logos.tsx": $$$$$$17,
    "deco-sites/ecannadeco/sections/Content/Partners.tsx": $$$$$$18,
    "deco-sites/ecannadeco/sections/Content/RichText.tsx": $$$$$$19,
    "deco-sites/ecannadeco/sections/Content/Support.tsx": $$$$$$20,
    "deco-sites/ecannadeco/sections/Content/Table.tsx": $$$$$$21,
    "deco-sites/ecannadeco/sections/Content/Testimonials.tsx": $$$$$$22,
    "deco-sites/ecannadeco/sections/Content/TextWithImage.tsx": $$$$$$23,
    "deco-sites/ecannadeco/sections/Footer/Footer.tsx": $$$$$$24,
    "deco-sites/ecannadeco/sections/Gallery.tsx": $$$$$$25,
    "deco-sites/ecannadeco/sections/Header/Header.tsx": $$$$$$26,
    "deco-sites/ecannadeco/sections/Images/BannerGrid.tsx": $$$$$$27,
    "deco-sites/ecannadeco/sections/Images/Carousel.tsx": $$$$$$28,
    "deco-sites/ecannadeco/sections/Images/ImageGallery.tsx": $$$$$$29,
    "deco-sites/ecannadeco/sections/Images/ShoppableBanner.tsx": $$$$$$30,
    "deco-sites/ecannadeco/sections/Layout/Container.tsx": $$$$$$31,
    "deco-sites/ecannadeco/sections/Layout/Flex.tsx": $$$$$$32,
    "deco-sites/ecannadeco/sections/Layout/Grid.tsx": $$$$$$33,
    "deco-sites/ecannadeco/sections/Layout/GridItem.tsx": $$$$$$34,
    "deco-sites/ecannadeco/sections/Links/LinkTree.tsx": $$$$$$35,
    "deco-sites/ecannadeco/sections/Links/Shortcuts.tsx": $$$$$$36,
    "deco-sites/ecannadeco/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$37,
    "deco-sites/ecannadeco/sections/Miscellaneous/Checkout.tsx": $$$$$$38,
    "deco-sites/ecannadeco/sections/Miscellaneous/ChoosePlanSignup.tsx":
      $$$$$$39,
    "deco-sites/ecannadeco/sections/Miscellaneous/ConfirmForgotPassword.tsx":
      $$$$$$40,
    "deco-sites/ecannadeco/sections/Miscellaneous/ConfirmSignup.tsx": $$$$$$41,
    "deco-sites/ecannadeco/sections/Miscellaneous/CookieConsent.tsx": $$$$$$42,
    "deco-sites/ecannadeco/sections/Miscellaneous/EcannaCardPage.tsx": $$$$$$43,
    "deco-sites/ecannadeco/sections/Miscellaneous/ForgotPassword.tsx": $$$$$$44,
    "deco-sites/ecannadeco/sections/Miscellaneous/MyAccount.tsx": $$$$$$45,
    "deco-sites/ecannadeco/sections/Miscellaneous/MyDocs.tsx": $$$$$$46,
    "deco-sites/ecannadeco/sections/Miscellaneous/MyInfo.tsx": $$$$$$47,
    "deco-sites/ecannadeco/sections/Miscellaneous/PrivatePageControl.tsx":
      $$$$$$48,
    "deco-sites/ecannadeco/sections/Miscellaneous/PublicPageControl.tsx":
      $$$$$$49,
    "deco-sites/ecannadeco/sections/Miscellaneous/PublicProfile.tsx": $$$$$$50,
    "deco-sites/ecannadeco/sections/Miscellaneous/SignIn.tsx": $$$$$$51,
    "deco-sites/ecannadeco/sections/Miscellaneous/Signout.tsx": $$$$$$53,
    "deco-sites/ecannadeco/sections/Miscellaneous/SignUp.tsx": $$$$$$52,
    "deco-sites/ecannadeco/sections/Miscellaneous/Slide.tsx": $$$$$$54,
    "deco-sites/ecannadeco/sections/Miscellaneous/UserAlerts.tsx": $$$$$$55,
    "deco-sites/ecannadeco/sections/Miscellaneous/UserAssociatedSignup.tsx":
      $$$$$$56,
    "deco-sites/ecannadeco/sections/Newsletter/Newsletter.tsx": $$$$$$57,
    "deco-sites/ecannadeco/sections/Product/ImageGalleryFrontBack.tsx":
      $$$$$$58,
    "deco-sites/ecannadeco/sections/Product/ImageGallerySlider.tsx": $$$$$$59,
    "deco-sites/ecannadeco/sections/Product/NotFound.tsx": $$$$$$60,
    "deco-sites/ecannadeco/sections/Product/NotFoundChallenge.tsx": $$$$$$61,
    "deco-sites/ecannadeco/sections/Product/ProductDetails.tsx": $$$$$$62,
    "deco-sites/ecannadeco/sections/Product/ProductInfo.tsx": $$$$$$63,
    "deco-sites/ecannadeco/sections/Product/ProductShelf.tsx": $$$$$$64,
    "deco-sites/ecannadeco/sections/Product/ProductShelfTabbed.tsx": $$$$$$65,
    "deco-sites/ecannadeco/sections/Product/SearchResult.tsx": $$$$$$66,
    "deco-sites/ecannadeco/sections/Product/ShelfWithImage.tsx": $$$$$$67,
    "deco-sites/ecannadeco/sections/Product/Wishlist.tsx": $$$$$$68,
    "deco-sites/ecannadeco/sections/Social/InstagramPosts.tsx": $$$$$$69,
    "deco-sites/ecannadeco/sections/Social/WhatsApp.tsx": $$$$$$70,
    "deco-sites/ecannadeco/sections/Theme/Theme.tsx": $$$$$$71,
  },
  "actions": {
    "deco-sites/ecannadeco/actions/changePassword.ts": $$$$$$$$$0,
    "deco-sites/ecannadeco/actions/checkout.ts": $$$$$$$$$1,
    "deco-sites/ecannadeco/actions/cognitoSignIn.ts": $$$$$$$$$2,
    "deco-sites/ecannadeco/actions/cognitoSignUp.ts": $$$$$$$$$3,
    "deco-sites/ecannadeco/actions/confirmCognitoSignup.ts": $$$$$$$$$4,
    "deco-sites/ecannadeco/actions/confirmForgotPassword.ts": $$$$$$$$$5,
    "deco-sites/ecannadeco/actions/createTicket.ts": $$$$$$$$$6,
    "deco-sites/ecannadeco/actions/deleteDocument.ts": $$$$$$$$$7,
    "deco-sites/ecannadeco/actions/forgotPassword.ts": $$$$$$$$$8,
    "deco-sites/ecannadeco/actions/getAssociation.ts": $$$$$$$$$9,
    "deco-sites/ecannadeco/actions/getCids.ts": $$$$$$$$$10,
    "deco-sites/ecannadeco/actions/getDocs.ts": $$$$$$$$$11,
    "deco-sites/ecannadeco/actions/getPlans.ts": $$$$$$$$$12,
    "deco-sites/ecannadeco/actions/getProfile.ts": $$$$$$$$$13,
    "deco-sites/ecannadeco/actions/getUser.ts": $$$$$$$$$14,
    "deco-sites/ecannadeco/actions/resendConfirmationCode.ts": $$$$$$$$$15,
    "deco-sites/ecannadeco/actions/updateProfile.ts": $$$$$$$$$16,
    "deco-sites/ecannadeco/actions/updateUserData.ts": $$$$$$$$$17,
    "deco-sites/ecannadeco/actions/uploadFile.ts": $$$$$$$$$18,
  },
  "apps": {
    "deco-sites/ecannadeco/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/ecannadeco/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/ecannadeco",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
